// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJKdZJ0XldZsJeGg51X3Lb1aDTiUpiriI',
    appId: '1:922415814604:web:789bc763d59a15d96eaf69',
    messagingSenderId: '922415814604',
    projectId: 'rentflow-c6ca0',
    authDomain: 'rentflow-c6ca0.firebaseapp.com',
    storageBucket: 'rentflow-c6ca0.firebasestorage.app',
    measurementId: 'G-S6QF4S3Y6H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhDr7koVzSzxHTNufH0aOKl31BjkTTyRs',
    appId: '1:922415814604:android:04c39085a78f79916eaf69',
    messagingSenderId: '922415814604',
    projectId: 'rentflow-c6ca0',
    storageBucket: 'rentflow-c6ca0.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGO_5qlTI6sxjkyhtwQebBM4PWSfJUBM8',
    appId: '1:922415814604:ios:6bd5c27901297a046eaf69',
    messagingSenderId: '922415814604',
    projectId: 'rentflow-c6ca0',
    storageBucket: 'rentflow-c6ca0.firebasestorage.app',
    iosBundleId: 'com.rentflow.rentflow',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGO_5qlTI6sxjkyhtwQebBM4PWSfJUBM8',
    appId: '1:922415814604:ios:6bd5c27901297a046eaf69',
    messagingSenderId: '922415814604',
    projectId: 'rentflow-c6ca0',
    storageBucket: 'rentflow-c6ca0.firebasestorage.app',
    iosBundleId: 'com.rentflow.rentflow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJKdZJ0XldZsJeGg51X3Lb1aDTiUpiriI',
    appId: '1:922415814604:web:c2c78ff7623347076eaf69',
    messagingSenderId: '922415814604',
    projectId: 'rentflow-c6ca0',
    authDomain: 'rentflow-c6ca0.firebaseapp.com',
    storageBucket: 'rentflow-c6ca0.firebasestorage.app',
    measurementId: 'G-PRTPVDH3DW',
  );
}
